# Generated by Django 4.2.6 on 2023-10-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.IntegerField()),
                ('classfication', models.CharField(max_length=255)),
                ('defense', models.IntegerField()),
                ('height_m', models.FloatField(blank=True, null=True)),
                ('hp', models.IntegerField()),
                ('japanese_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('pokedex_number', models.IntegerField()),
                ('sp_attack', models.IntegerField()),
                ('sp_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('type1', models.CharField(max_length=255)),
                ('type2', models.CharField(blank=True, max_length=255, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('generation', models.IntegerField()),
                ('is_legendary', models.BooleanField()),
            ],
        ),
    ]
